# Created with WinGet Releaser using komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Neosku.AviUtl2-Catalog
PackageVersion: 0.3.0
PackageLocale: ja-JP
Publisher: Neosku
PublisherUrl: https://github.com/Neosku
PublisherSupportUrl: https://github.com/Neosku/aviutl2-catalog/issues
Author: Neosku
PackageName: AviUtl2 カタログ
PackageUrl: https://github.com/Neosku/aviutl2-catalog
License: MIT
LicenseUrl: https://github.com/Neosku/aviutl2-catalog/blob/HEAD/LICENSE
Copyright: Copyright (c) 2025 Neosku
ShortDescription: AviUtl2 のプラグインやスクリプトを、検索・インストール・アップデートまで一括管理できるデスクトップ向けカタログアプリです。
Description: AviUtl2 のプラグインやスクリプトを、検索・インストール・アップデートまで一括管理できるデスクトップ向けカタログアプリです。
Moniker: aviutl2-catalog
Tags:
- aviutl2
- manager
- plugin
- script
- video
ReleaseNotes: |-
  スクリーンショット 2026-01-10 173057
  ✨ 新機能
  - UIを全面的に再設計し、デザインを刷新
  - 人気順で表示する機能を追加
  - BOOTHで配布されているパッケージを導入する機能を追加
  - パッケージ一覧のエクスポート／インポート機能を追加
  - AviUtl2 を起動できるボタンを追加
  🛠 修正・改善
  - カスタムライセンス名を指定できない問題を修正
  - CC0 1.0 のライセンステンプレートを追加
ReleaseNotesUrl: https://github.com/Neosku/aviutl2-catalog/releases/tag/v0.3.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
