# Created with WinGet Releaser using komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: RubyMetric.chsrc
PackageVersion: 0.2.4
PackageLocale: zh-CN
Publisher: RubyMetric
PublisherUrl: https://github.com/RubyMetric
PublisherSupportUrl: https://github.com/RubyMetric/chsrc/issues
PackageName: chsrc
PackageUrl: https://github.com/RubyMetric/chsrc
License: GPL-3.0
ShortDescription: chsrc 全平台通用换源工具与框架.
Tags:
- archlinux
- brew
- bsd
- c99
- cargo
- composer
- cpan
- debian
- fedora
- flathub
- gem
- guix
- linux
- macos
- maven
- nix
ReleaseNotes: |-
  该附件二进制文件为预编译供用户提前使用
  版本：v0.2.4
  日期：2025-12-31
  更新：v0.2.3...v0.2.4
  内容：
  这是2025年最后一个版本，恭祝大家2026年元旦快乐！🎉
  1. 修复 Android 系统检测
  2. 改善 xy 内存分配与回收
  3. 使用 C 语言重写 prepend to file 逻辑
  4. 尽量使用 PowerShell v7，后备使用 PowerShell v5
  换源方法(recipe):
  1. 修复 Mac 上 uv 换源
  2. 在 Windows 上使用 PowerShell 替代 sed 和 grep 来处理 uv
  3. 在 Windows 上额外检测 python3 命令是否为微软商店占位符
  源：
  1. 修复 Rust Cargo 测速链接 404 的问题
  2. 修复 Debian 某源多余的后缀
  3. 添加 Perl 精准测速链接
  新贡献者
  - @MingriLingran made their first contribution in #328
ReleaseNotesUrl: https://github.com/RubyMetric/chsrc/releases/tag/v0.2.4
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/RubyMetric/chsrc/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
