# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: PCLCommunity.PCL2-CE.Beta
PackageVersion: 2.13.0-beta.1
PackageLocale: en-US
Publisher: PCLCommunity
PublisherUrl: https://github.com/PCL-Community
PublisherSupportUrl: https://github.com/PCL-Community/PCL2-CE/issues
PackageName: Plain Craft Launcher Community Beta Edition
PackageUrl: https://github.com/PCL-Community/PCL2-CE
License: 专有软件
LicenseUrl: https://github.com/PCL-Community/PCL2-CE/blob/2.12.0-beta.15/LICENCE
Copyright: Copyright © 龙腾猫跃 2016. All Rights Reserved.
ShortDescription: Plain Craft Launcher Community Edition
Tags:
- community-edition
- csharp-app
- game-launcher
- java
- launcher
- minecraft
- minecraft-java-edition
- minecraft-launcher
- net-framework
- pcl2
- plain-craft-launcher
- vb-net
ReleaseNotes: |-
  2.13.0-beta.1 更新一览(2025-08-24)
  ⚠️ 破坏性更改
  Important
  自 2.13.0 起，PCL CE 将需要 .NET 8 桌面运行时才能运行。
  如果你还未安装，请下载并安装 .NET 8 桌面运行时。
  🚀 新功能
  - authlib: 添加预设服务器 (#1410)
  - ui: 支持自定义视频背景功能 (#1401)
  🐛 问题修复
  - ui: 部分列表在卡片中的 Margin 不统一 (#1388)
  - 修复 Shell 打开路径行为 (#1407)
  - ui: 修复 IsEditable = true 的 MyComboBox 光标颜色有误 (#1416)
  - authlib: 修复一些Bug (#1423)
  - authlib: 第三方登录使用拖拽设置服务器下无法选择其他角色登录 (#1411)
  🚜 重构
  - Update framework to net 8 (#1320)
  - 使用更现代的 API (#1405)
  - link: 重构大厅到 Core (#1374)
  📚 文档修改
  - README: 添加支持平台表格 [skip ci]
  - README: 需要 .NET 9 SDK 才能编译 [skip ci]
  ⚙️ 其他小改动
  - 移除 vbproj 中的 My Project 引用
  - PageLinkLobby: 微调文字位置
  如果你有 Mirror 酱 CDK 可以直接使用此高速下载源
  你也可以直接在下方的 Assets 中下载
ReleaseNotesUrl: https://github.com/PCL-Community/PCL2-CE/releases/tag/2.13.0-beta.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/PCL-Community/PCL2-CE/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
