# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Game1024.OpenSpeedy
PackageVersion: 1.7.8
PackageLocale: en-US
Publisher: Game1024
PublisherUrl: https://github.com/game1024
PublisherSupportUrl: https://github.com/game1024/OpenSpeedy/issues
PackageName: OpenSpeedy
PackageUrl: https://github.com/game1024/OpenSpeedy
License: GPL-3.0
LicenseUrl: https://github.com/game1024/Speedy/blob/HEAD/LICENSE
ShortDescription: 🎮 An open-source game speed modifier.[一款开源的游戏变速器]
Tags:
- cplusplus
- gamedev
- gamemod
- pc
- qt
- speed-engine
- toolkit
- windows
ReleaseNotes: |-
  - 修复：托盘菜单项翻译
  - 新增：深色主题颜色
  - 优化：快捷键加速时的声音延迟问题
  深色主题预览
  PixPin_2025-12-21_17-49-13
ReleaseNotesUrl: https://github.com/game1024/Speedy/releases/tag/v1.7.8
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/game1024/OpenSpeedy/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
