# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: PCLCommunity.PCL2-CE
PackageVersion: 2.13.0
PackageLocale: en-US
Publisher: PCLCommunity
PublisherUrl: https://github.com/PCL-Community
PublisherSupportUrl: https://github.com/PCL-Community/PCL2-CE/issues
PackageName: Plain Craft Launcher Community Edition
PackageUrl: https://github.com/PCL-Community/PCL2-CE
License: 专有软件
LicenseUrl: https://github.com/PCL-Community/PCL2-CE/blob/2.11.9/LICENCE
Copyright: Copyright © 龙腾猫跃 2016. All Rights Reserved.
ShortDescription: Plain Craft Launcher Community Edition
Tags:
- community-edition
- csharp-app
- game-launcher
- java
- launcher
- minecraft
- minecraft-java-edition
- minecraft-launcher
- net-framework
- pcl2
- plain-craft-launcher
- vb-net
ReleaseNotes: |-
  2.13.0 更新一览(2025-10-03)
  ⚠️ 破坏性更改
  Important
  自 2.13.0 起，PCL CE 将需要 .NET 8 桌面运行时才能运行。
  如果你还未安装，请下载并安装 .NET 8 桌面运行时。
  🚀 新功能
  - link: 对联机启动代码的小优化 (#1547)
  - launch: 支持全局设置游戏渲染器，并将警告提示改为弹窗 (#1565)
  - link: 使用组播接收代替主动端口探测，防止一些意外情况
  - 加入服务器 MOTD 文本的深色模式判断
  - 部分优化查询服务器和资源包格式化文本在深色模式下的阅读体验
  - link: 大厅公告支持识别启动器版本精准推送 (#1588)
  - 加入更有可读性的版本号显示 (#1622)
  - instance: 将实例列表中的实例信息改为 Tag 形式 (#1623)
  - download: 修改 Mod Loader 手动安装包下载逻辑 (#1619)
  - link: 修复一个意外的文件检测 (#1625)
  - announcement: 支持启动器公告主页 (#1616)
  🐛 问题修复
  - http: 由于 HTTP 版本协商部分时候存在异常，默认使用 HTTP/2 作为最高协商版本
  - form: 为什么窗口大小改变处理要监听 Loaded 事件
  - 修复老版本 MC 启动代理参数应用不正确
  - export-config: 取消导出导致启动器崩溃
  - other-test: 修复人品值为 100 时弹窗内容没有正确换行的问题
  - serverQuery: 针对中文冒号兜底 (#1586)
  - config-export: 导出配置文件行为存在异常 (#1597)
  - 修复自动切换中文低版本不起效 (#1605)
  - 清理过期代码
  - launch: 修复部分 MMC 整合包无法启动的问题 (#1613)
  - link: 下载联机组件可能导致控件意外激活 (#1585)
  - 禁用回收站删除进度框以避免触发巨硬的史山代码 (#1626)
  - 缓解旧版本启动检测问题
  - mod-search: 修复 Curseforge 传入的参数作用重复问题 (#1628)
  - instance: 修复实例列表 UI 细节问题和搜索无结果问题 (#1633)
  - 在功能隐藏中加入服务器 (#1634)
  📚 文档修改
  - Readme 添加统计信息 & 优化
  ⚡ 性能优化
  - comp: 异步执行本地资源加载的耗时操作 (#1624)
  🎨 部分样式调整
  - profile: 重命名档案系统变量以符合命名规范 (#1632)
  ⚙️ 其他小改动
  - 升级部分包版本
  - mcmod: 同步更新模组数据库
  - Fix typo in JavaService
  - Disable some useless warning
  - 优化 issue 模板
  - java: 优化代码结构 (#1602)
  如果你有 Mirror 酱 CDK 可以直接使用此高速下载源
  你也可以直接在下方的 Assets 中下载
ReleaseNotesUrl: https://github.com/PCL-Community/PCL2-CE/releases/tag/2.13.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/PCL-Community/PCL2-CE/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
