# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: PCLCommunity.PCL2-CE
PackageVersion: 2.12.1
PackageLocale: en-US
Publisher: PCLCommunity
PublisherUrl: https://github.com/PCL-Community
PublisherSupportUrl: https://github.com/PCL-Community/PCL2-CE/issues
PackageName: Plain Craft Launcher Community Edition
PackageUrl: https://github.com/PCL-Community/PCL2-CE
License: 专有软件
LicenseUrl: https://github.com/PCL-Community/PCL2-CE/blob/2.11.9/LICENCE
Copyright: Copyright © 龙腾猫跃 2016. All Rights Reserved.
ShortDescription: Plain Craft Launcher Community Edition
Tags:
- community-edition
- csharp-app
- game-launcher
- java
- launcher
- minecraft
- minecraft-java-edition
- minecraft-launcher
- net-framework
- pcl2
- plain-craft-launcher
- vb-net
ReleaseNotes: |-
  🚀 新功能
  - link: 提高连接的等待时间  -  by @tangge233 (309b0)
  - mc-server: 独立的 Minecraft 服务器查询控件  -  by @tangge233 in #1274 (4597c)
  - select-left: 添加文件夹列表排序  -  by @pynickle in #1251 (654c5)
     🐛 修复
  - Typo of mcimirrmr  -  by @Silverteal in #1292 (e025e)
  - launch:
    - 意外提示登录失败  -  by @tangge233 (24ffa)
  - link:
    - 可能因为一些信息未能获取到错误地判定大厅不存在  -  by @tangge233 in #1296 (c6a07)
    - 输出重定向导致的 ET 在部分情况下卡住  -  by @tangge233 in #1304 (0cd9e)
    - 为 web 服务端初始化添加日志和异常处理  -  by @ruattd in #1290 (cdbdc)
     🛠️ 改进
  - 删除单例检查  -  by @ruattd in #1300 (5c765)
  - OtherTest: 删除无用的刷新缓存按钮  -  by @pynickle in #1276 (a3b54)
     🎨 代码样式
  - 一个巨大的 typo 修复  -  by @pynickle in #1293 (0e0f3)
  - PageOtherFeedback.xaml.vb下部分符号错误问题  -  by @qfys521 in #1302 (73cfc)
      View changes on GitHub
  如果你有 Mirror 酱 CDK 可以直接使用此高速下载源
  你也可以直接在下方的 Assets 中下载
ReleaseNotesUrl: https://github.com/PCL-Community/PCL2-CE/releases/tag/2.12.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/PCL-Community/PCL2-CE/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
