# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: OneKey.OneKey
PackageVersion: 5.18.0
PackageLocale: en-US
Publisher: OneKey
PublisherUrl: https://github.com/OneKeyHQ
PublisherSupportUrl: https://github.com/OneKeyHQ/app-monorepo/issues
Author: OneKeyHQ
PackageName: OneKey Wallet
PackageUrl: https://github.com/OneKeyHQ/app-monorepo
License: Copyright ONEKEY LIMITED (Hong Kong) All rights reserved.
LicenseUrl: https://github.com/OneKeyHQ/app-monorepo/blob/HEAD/LICENSE.md
ShortDescription: Multi-chain support for BTC/ETH/BNB/NEAR/Polygon/Solana/Avalanche/Fantom and others
Tags:
- bitcoin
- blockchain
- defi
- electron
- react
- wallet
- web
ReleaseNotes: |-
  ✨ New Features
  - Added Perp rebate feature.
  - Added Base chain NFT support.
  - Added margin mode for Perp.
  💎 Improvements
  - Optimized Swap quoting logic and improved slippage retrieval speed.
  - Redesigned Earn / DeFi detail page and Portfolio page with performance improvements.
  - Improved Market UI and interactions and now remembers the user's last selected tab.
  - “Recently used” is now fixed at the top of the network selector.
  - ADA staking frozen balance is now displayed.
  - Improved network stability.
  🐞 Bug Fixes
  - Fixed style issues in rebate external jump modal.
  - Fixed wording issues in the create-password popup and settings page.
  - Fixed issue where opening OneKey via deeplink on cold start could not navigate to the target page.
  - Fixed startup error after installing Linux snap package.
  - Fixed Linux snap WebUSB not detecting hardware devices.
  ✨ 新功能
  - 新增 Perp 返佣功能。
  - 支持 Base 链 NFT。
  - Perp 新增保证金模式。
  💎 改进
  - 优化 Swap 询价逻辑，并提升获取滑点的速度。
  - Earn / DeFi 模块详情页与 Portfolio 页改版，同时进行性能优化。
  - 优化行情页面 UI 与交互，记住用户最后选择的 Tab。
  - 网络选择器中将「最近使用」固定展示在列表顶部。
  - ADA 资产支持显示质押冻结余额。
  - 支持更稳定的网络连接。
  🐞 问题修复
  - 修复返佣外部跳转弹窗的样式显示问题。
  - 修复创建密码弹窗与设置页面的文案问题。
  - 修复通过 deeplink 冷启动 OneKey 后无法进入指定页面的问题。
  - 修复 Linux snap 包安装后启动报错的问题。
  - 修复 Linux snap 客户端 WebUSB 无法搜索到硬件的问题。
ReleaseNotesUrl: https://github.com/OneKeyHQ/app-monorepo/releases/tag/v5.18.0
ManifestType: defaultLocale
ManifestVersion: 1.10.0
