# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: PCLCommunity.PCL2-CE.Beta
PackageVersion: 2.12.3-beta.2
PackageLocale: en-US
Publisher: PCLCommunity
PublisherUrl: https://github.com/PCL-Community
PublisherSupportUrl: https://github.com/PCL-Community/PCL2-CE/issues
PackageName: Plain Craft Launcher Community Beta Edition
PackageUrl: https://github.com/PCL-Community/PCL2-CE
License: 专有软件
LicenseUrl: https://github.com/PCL-Community/PCL2-CE/blob/2.12.0-beta.15/LICENCE
Copyright: Copyright © 龙腾猫跃 2016. All Rights Reserved.
ShortDescription: Plain Craft Launcher Community Edition
Tags:
- community-edition
- csharp-app
- game-launcher
- java
- launcher
- minecraft
- minecraft-java-edition
- minecraft-launcher
- net-framework
- pcl2
- plain-craft-launcher
- vb-net
ReleaseNotes: |-
  2.12.3-beta.2 更新一览(2025-08-16)
  🐛 问题修复
  - comp-resource: 修改模组启用状态会导致崩溃
  - setup: 导入导出设置功能异常
  - setup: 配置文件部分数据类型编写错误
  ⚙️ 其他小改动
  - ci: 换一个更新日志制作器的部署脚本
  - ci: 限制生成的更新日志的范围
  如果你有 Mirror 酱 CDK 可以直接使用此高速下载源
  你也可以直接在下方的 Assets 中下载
ReleaseNotesUrl: https://github.com/PCL-Community/PCL2-CE/releases/tag/2.12.3-beta.2
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/PCL-Community/PCL2-CE/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
