# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: PCLCommunity.PCL2-CE
PackageVersion: 2.13.3
PackageLocale: en-US
Publisher: PCLCommunity
PublisherUrl: https://github.com/PCL-Community
PublisherSupportUrl: https://github.com/PCL-Community/PCL2-CE/issues
PackageName: Plain Craft Launcher Community Edition
PackageUrl: https://github.com/PCL-Community/PCL2-CE
License: 专有软件
LicenseUrl: https://github.com/PCL-Community/PCL2-CE/blob/2.11.9/LICENCE
Copyright: Copyright © 龙腾猫跃 2016. All Rights Reserved.
ShortDescription: Plain Craft Launcher Community Edition
Tags:
- community-edition
- csharp-app
- game-launcher
- java
- launcher
- minecraft
- minecraft-java-edition
- minecraft-launcher
- net-framework
- pcl2
- plain-craft-launcher
- vb-net
ReleaseNotes: |-
  2.13.3 更新一览(2025-10-05)
  ⚠️ 破坏性更改
  Important
  自 2.13.0 起，PCL CE 将需要 .NET 8 桌面运行时才能运行。
  如果你还未安装，请下载并安装 .NET 8 桌面运行时。
  🐛 问题修复
  - 移除 On Error Resume Next (#1644)
  - comp: 修复 CurseForge 搜索排序不生效的问题 (#1651)
  - 修复 Java 列表可能意外移除 Java 的问题
  - 修复可能无法找到部分 MC 局域网实例的问题
  - 修复资源搜索中文识别的问题（这导致了不显示部分结果）
  - 修复部分情况下退出启动器后存在后台残留进程的问题
  - 修复无法读取 1.21.9 世界数据 (#1656)
  - 修复未有游戏启动时清理垃圾出现错误的提示 (#1659)
  - 修复切换渲染器警告点击取消后仍进行切换的问题 (#1666)
  - 软渲染弹窗判断逻辑有误
  ⚙️ 其他小改动
  - java: 减少管理页面中重复加载次数
  - 修改一处 UI 文本
  ◀️ 回退改动
  - 9c6896b
  如果你有 Mirror 酱 CDK 可以直接使用此高速下载源
  你也可以直接在下方的 Assets 中下载
ReleaseNotesUrl: https://github.com/PCL-Community/PCL2-CE/releases/tag/2.13.3
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/PCL-Community/PCL2-CE/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
