# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: PCLCommunity.PCL2-CE.Beta
PackageVersion: 2.12.3-beta.1
PackageLocale: en-US
Publisher: PCLCommunity
PublisherUrl: https://github.com/PCL-Community
PublisherSupportUrl: https://github.com/PCL-Community/PCL2-CE/issues
PackageName: Plain Craft Launcher Community Beta Edition
PackageUrl: https://github.com/PCL-Community/PCL2-CE
License: 专有软件
LicenseUrl: https://github.com/PCL-Community/PCL2-CE/blob/2.12.0-beta.15/LICENCE
Copyright: Copyright © 龙腾猫跃 2016. All Rights Reserved.
ShortDescription: Plain Craft Launcher Community Edition
Tags:
- community-edition
- csharp-app
- game-launcher
- java
- launcher
- minecraft
- minecraft-java-edition
- minecraft-launcher
- net-framework
- pcl2
- plain-craft-launcher
- vb-net
ReleaseNotes: |-
  2.12.3-beta.1 更新一览(2025-08-15)
  🚀 新功能
  - ShaderPack: 可单独选择光影加载器 (#1311)
  - page-instance-setup: 自动将服务器地址替换为半角冒号 (#1299)
  - link: 更换 QA 页面 (#1325)
  - link: 允许在有多个 ET 实例的情况下与正确的 ET 实例通讯 (#1328)
  - identify: 将识别码移入 Core 中
  - link: 更新 EasyTier 到 2.4.2 (#1342)
  - modBase-hash: 哈希计算使用 Core 内提供的方法
  - CompItem: 优化收藏图标显示 (#1260)
  - instance-manage: 支持修补核心文件 (#1272)
  - yggdrasil: ALI 支持 (#1352)
  - link: EasyTier 版本不同时发出警告
  - encoding: 简易文本编码检测(仍需后续优化)
  🐛 问题修复
  - Instance: 修复官方启动器文件夹类型判断错误 (#1307)
  - 修复 (Legacy) Fabric API 的选择框下端间隔不正常 (#1315)
  - link: 连接到陶瓦用户的大厅时部分文本显示异常 (#1308)
  - text: 忘记改上游版本号了
  - ms-login: 可能会误认为 AccessToken 为 null 的用户为已登录用户
  - update-branch: 修正 SystemSystemUpdateBranch 的逻辑 (#1351)
  - link: 转发有时候会抽风
  - mainpage: 之前修改了配置模型中的配置项键名但是忘了改调用方的 (#1354)
  - download: 可能会由于 uvmc 列表加载失败导致最终列表都无法展示
  🚜 重构
  - 再次重新规划分类与命名空间
  - Setup: 迁移配置系统 (#1313)
  - setup: 迁移 SystemSystemUpdateBranch (#1349)
  - ui: 重写字体选择框加载逻辑 (#1350)
  ⚡ 性能优化
  - SavesInfo: 加入存档信息缓存 (#1268)
  🎨 部分样式调整
  - link: 让代码更加简洁
  - 去除中文逗号 (#1356)
  - mod-base: 提高代码的一点可维护性……
  ⚙️ 其他小改动
  - Webp: 提供 Decoder 静态实例，减少重复实例化加载负担
  - 完善带有 Async 修饰的异步逻辑
  - 修改 Mirror 酱介绍文本，减少不熟悉的用户对此的误解的概率
  - 更新解决方案的配置引用
  - ci: 换用 git cliff 作为更新日志生成工具
  - link: 下调房间查找失败重试次数和重试时间
  如果你有 Mirror 酱 CDK 可以直接使用此高速下载源
  你也可以直接在下方的 Assets 中下载
ReleaseNotesUrl: https://github.com/PCL-Community/PCL2-CE/releases/tag/2.12.3-beta.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/PCL-Community/PCL2-CE/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
